title: Create REST server with NodeJS and Express
tagline: Learn the basics to create an Express server and follow the REST principles.
description: Learn the basics to create an Express server and follow the REST principles.

tags:
  - NodeJS
  - JavaScript
  - Express
  - Server

template:
  name: hyf-homework-nodejs-3
  repo: hyf-homework-express

before:

- type: updateBranchProtection
  required_status_checks:
    strict: true
    contexts:
      - 'Travis CI - Branch'

  # open issue 1 (welcome)
- type: createIssue
  title: Welcome
  body: 00-intro.md
  data:
    prUrl: '%payload.repository.html_url%/compare/master...step-1?expand=1'


steps:
  # 1 - Enable CI
- title: Create the first endpoint
  description: Enable continuous integration and make the first endpoint.
  link: '{{ repoUrl }}/issues/1'
  event: check_run
  actions:
  # waits for ci to report a status, any status
  - type: gate
    left: '%payload.check_run.app.name%'
    operator: ===
    right: Travis CI

  - type: gate
    left: '%payload.check_run.pull_requests.length%'
    operator: '>'
    right: 0

  - type: respond
    issue: '%payload.check_run.pull_requests.0.number%'
    with: 00_01-build-status.md

- title: Create a Server and fix the build
  description: Create a Server that would respond with Hello World!
  link: '{{ repoUrl }}/pull/2'
  event: check_run.completed
  actions:

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success

  # The build pass then we approve the PR
  - type: gate
    left: '%payload.check_run.pull_requests.0.number%'
    operator: ==
    right: 2

  # approve PullRequest
  - type: createReview
    body: 01_01-build-pass.md
    pullRequest: 2
    event: APPROVE

- title: Merge Pull Request
  description: Merge PullRequest "Hello World!"
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.closed
  actions:

  # We merge the PR then we create the next issue
  - type: gate
    left: '%payload.pull_request.number%'
    operator: ===
    right: 2

  # update step-2
  - type: mergeBranch
    head: master
    base: step-2

  # close initial issue
  - type: closeIssue
    issue: Welcome

  # open issue #4
  - type: createIssue
    title: First REST method
    body: 02-intro.md
    action_id: linkGetUserEndpointIssue
    data:
      prUrl: '%payload.repository.html_url%/compare/master...step-2?expand=1'

  - type: respond
    with: 01_02-merged.md
    data:
      getUsersEndpointIssue: '%actions.linkGetUserEndpointIssue.data.html_url%'

# Make PR for /users endpoint
- title: Create PR for GET /users
  description: Add endpoint to fetch all users
  link: '{{ repoUrl }}/issue/2'
  event: pull_request.opened
  actions:

  # open pr #3
  - type: respond
    with: 02_01-pull-request.md

# Make the /users endpoint
- title: First step in the business logic, GET /users
  description: Deliver your first REST endpoint!
  link: '{{ repoUrl }}/pull/4'
  event: check_run.completed
  actions:

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.check_run.pull_requests.0.number%'
    operator: ==
    right: 4

  # approve PullRequest
  - type: createReview
    body: 02_02-get-users-pass.md
    pullRequest: 4
    event: APPROVE

- title: Merge /users Pull Request
  description: Merge the pull request!
  link: '{{ repoUrl }}/pull/4'
  event: pull_request.closed
  actions:

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.pull_request.number%'
    operator: ==
    right: 4

  # Update issue #4 with step-3
  - type: mergeBranch
    head: master
    base: step-3

  # Instructions: POST /user
  - type: respond
    with: 03-intro.md
    issue: 3
    data:
      prUrl: '%payload.repository.html_url%/compare/master...step-3?expand=1'

# Make PR for /users endpoint
- title: Create PR for GET and POST /user
  description: Add endpoint to fetch and create a user
  link: '{{ repoUrl }}/issue/3'
  event: pull_request.opened
  actions:

  # open pr #3
  - type: respond
    with: 03_01-pr-body.md

# Complete the POST and GET /user
- title: 'GET and POST /user'
  description: fix the tests!
  link: '{{ repoUrl }}/pull/5'
  event: check_run.completed
  actions:

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.check_run.pull_requests.0.number%'
    operator: ==
    right: 5

  # approve PullRequest
  - type: createReview
    body: 03_02-user-pass.md
    pullRequest: 5
    event: APPROVE

- title: 'Merge GET/POST /user Pull Request'
  description: merge the pull request
  link: '{{ repoUrl }}/pull/5'
  event: pull_request.closed
  actions:

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.pull_request.number%'
    operator: ==
    right: 5

  # Update issue #4 with step-3
  - type: mergeBranch
    head: master
    base: step-4

  # Instructions: DELETE /user
  - type: respond
    with: 04-intro.md
    issue: 3
    data:
      prUrl: '%payload.repository.html_url%/compare/master...step-4?expand=1'

# Make PR for /users endpoint
- title: Create PR for DELETE /user
  description: Add endpoint to fetch and create a user
  link: '{{ repoUrl }}/issue/3'
  event: pull_request.opened
  actions:

  # open pr #3
  - type: respond
    with: 04_01-pr-body.md

# Complete the DELETE /user
- title: 'DELETE /users'
  description: Allow your service to delet users
  link: '{{ repoUrl }}/pull/6'
  event: check_run.completed
  actions:

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success

  # The build pass and we create the next issue
  - type: gate
    left: '%payload.check_run.pull_requests.0.number%'
    operator: ==
    right: 6

  # approve PullRequest
  - type: createReview
    body: finish.md
    pullRequest: 6
    event: APPROVE

- title: 🎉 Course Complete
  description: Nice job!
  link: '{{ repoUrl }}/issue/4'
  event: pull_request.closed
  actions:

  - type: gate
    left: '%payload.pull_request.number%'
    operator: ==
    right: 6

  # close initial issue
  - type: closeIssue
    issue: First REST method
